apiVersion: v1
kind: Service
metadata:
  name: apiappointment-loadbalancer
spec:
  selector:
    app: apiappointment
  ports:
    - protocol: TCP
      port: 83
      targetPort: 83
  type: LoadBalancer